# Generated by Django 4.2 on 2024-09-09 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0003_alter_useretf_joined_date'),
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('individual', 'Individual'), ('corp', 'Corp')], default='individual', max_length=10),
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_corps', to=settings.AUTH_USER_MODEL)),
                ('etfs', models.ManyToManyField(related_name='corp_etfs', to='etfs.etf')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='userauths.corp'),
        ),
    ]
