# Generated by Django 4.2 on 2024-10-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_role',
        ),
    ]
