# Generated by Django 4.2 on 2024-10-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_types', to='Funds.fundcategorytype', to_field='subcategory_code'),
        ),
        migrations.AddField(
            model_name='fund',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='users',
            field=models.ManyToManyField(related_name='funds', through='Funds.UserFund', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfund',
            unique_together={('user', 'fund', 'joined_date')},
        ),
    ]
