# Generated by Django 4.2 on 2024-10-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funds', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_type',
        ),
    ]
