# Generated by Django 4.2 on 2024-08-23 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('etf_type', models.CharField(default='全球共享經濟ETF', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('lowest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('investment_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('state', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_etfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etfs.etf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'etf')},
            },
        ),
        migrations.AddField(
            model_name='etf',
            name='users',
            field=models.ManyToManyField(related_name='etfs', through='etfs.UserETF', to=settings.AUTH_USER_MODEL),
        ),
    ]
