# Generated by Django 5.0.7 on 2024-07-22 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('etf_type', models.CharField(default='全球共享經濟ETF', max_length=50)),
                ('fundraising_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('fundraising_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('exist_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('exist_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='比特幣', max_length=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0.5, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
