# Generated by Django 5.0.7 on 2024-07-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_etfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useretf',
            name='etf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etfs.etf'),
        ),
        migrations.AddField(
            model_name='useretf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etf',
            name='users',
            field=models.ManyToManyField(related_name='etfs', through='etfs.UserETF', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useretf',
            unique_together={('user', 'etf')},
        ),
    ]
