# Generated by Django 4.2 on 2024-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
