# Generated by Django 4.2 on 2024-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='announcement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='fundraising_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
