# Generated by Django 4.2 on 2024-09-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useretf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etf',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etfs', to='etfs.etfcategorytype'),
        ),
        migrations.AddField(
            model_name='etf',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_etfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etf',
            name='users',
            field=models.ManyToManyField(related_name='etfs', through='etfs.UserETF', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useretf',
            unique_together={('user', 'etf')},
        ),
    ]
