# Generated by Django 4.2 on 2024-09-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='category_type',
        ),
        migrations.AddField(
            model_name='etf',
            name='subcategory_code',
            field=models.ForeignKey(default='A1', on_delete=django.db.models.deletion.CASCADE, related_name='category_types', to='etfs.etfcategorytype', to_field='subcategory_code'),
            preserve_default=False,
        ),
    ]
