# Generated by Django 4.2 on 2024-08-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0002_alter_etf_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
