# Generated by Django 4.2 on 2024-10-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='lowest_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
