# Generated by Django 4.2 on 2024-08-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0002_etf_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='investment_cap',
        ),
        migrations.AlterField(
            model_name='etf',
            name='current_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etf',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etf',
            name='lowest_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
