# Generated by Django 4.2 on 2024-09-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretf',
            name='transaction_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
