# Generated by Django 4.2 on 2024-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0003_remove_etf_investment_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='current_investment',
            field=models.IntegerField(default=0),
        ),
    ]
