# Generated by Django 4.2 on 2024-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0003_alter_etf_lowest_amount_alter_etf_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='current_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
