# Generated by Django 4.2 on 2024-08-29 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0003_alter_etf_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='lowest_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
