# Generated by Django 4.2 on 2024-09-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0003_remove_etf_category_type_etf_subcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useretf',
            name='leave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
