# Generated by Django 4.2 on 2024-09-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '__first__'),
        ('etfs', '0003_alter_useretf_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etfs', to='corps.corp'),
        ),
    ]
