# Generated by Django 4.2 on 2024-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0004_alter_etf_current_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='lowest_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
