# Generated by Django 4.2 on 2024-09-20 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etfs', '0004_etf_corp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useretf',
            unique_together={('user', 'etf', 'joined_date')},
        ),
    ]
