# Generated by Django 4.2 on 2024-08-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0004_alter_etf_current_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='state',
        ),
    ]
