# Generated by Django 4.2 on 2024-09-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0004_useretf_leave_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etf',
            old_name='subcategory_code',
            new_name='category',
        ),
    ]
