# Generated by Django 4.2 on 2024-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0005_alter_useretf_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='total_invested',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useretf',
            name='investment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useretf',
            name='is_fundraising',
            field=models.BooleanField(default=False),
        ),
    ]
