# Generated by Django 4.2 on 2024-10-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0005_alter_etf_lowest_amount_alter_etf_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
