# Generated by Django 4.2 on 2024-09-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0006_etf_total_invested_useretf_investment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretf',
            name='is_fundraising',
            field=models.BooleanField(default=True),
        ),
    ]
