# Generated by Django 4.2 on 2024-09-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0007_alter_useretf_is_fundraising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useretf',
            name='is_fundraising',
        ),
    ]
