# Generated by Django 4.2 on 2024-08-26 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0008_etf_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='announcement_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='etf',
            name='fundraising_start_date',
            field=models.DateTimeField(),
        ),
    ]
