# Generated by Django 4.2 on 2024-09-23 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etfs', '0008_remove_useretf_is_fundraising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='lowest_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='etf',
            name='total_invested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
